### PR TITLE
Primes

### PR DESCRIPTION
**Pull request by scottpschaffer**
Dhru, Please have a look at Program.cs and see if it can be adjusted to fit your Integer code. I commented out everything except for Primes so that I could confirm that all my code ran and worked.

### CODE REVIEW

**Comment by jcockhren** [comment]
@scottpschaffer @dupender Hey. I don't see any evidence this PR was reviewed by anyone. What happened?

**Comment by dupender** [comment]
Scott/Jurnell,

I did not see this till after work today and looked on my GitHub it looks
like I don't have any pull requests....so not sure why that is?
Looks like it was approved by Blaise?

I don't have time at work to look at these or do any homework, Scott has
time to do this stuff at work.

Dhru

**Comment by scottpschaffer** [comment]
I need to talk with Blaise. I asked him to review my code and the next thing I know, the code is merged with Master by Blaise.
On Aug 5, 2016 7:15 PM, Jurnell Cockhren notifications@github.com wrote:@scottpschaffer @dupender Hey. I don't see any evidence this PR was reviewed by anyone. What happened?

**Comment by jcockhren** [comment]
@scottpschaffer Let's create another branch and PR to finish this.

**Pull request merged**
